spring.application.name=JWThandsOns
# Optional - change server port
server.port=8080
logging.level.root=info
logging.level.HandsOn5=debug


# Optional - show detailed logs
logging.level.org.springframework.security=DEBUG
spring.main.allow-bean-definition-overriding=true


