spring.application.name=O-RMapping
spring.datasource.url=jdbc:mysql://localhost:3307/ormdbMapping
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
