spring.application.name=CountryWebService1
# Set server port
server.port=8085

# Set logging level for the application package
logging.level.HandsOn3=DEBUG

# Log output format (optional, for better readability)
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
